FROM dtcpronto/ros-jazzy:full

RUN sudo apt update && sudo apt install -y \
 ros-jazzy-rtcm-msgs \
 python3-zmq \
 python3-serial

RUN pip3 install --break-system-packages pyrtcm

COPY ./rtk-correction ws/src/rtk-correction

RUN /bin/bash -c "\
    source /opt/ros/jazzy/setup.bash && \
    cd /home/dtc/ws && \
    colcon build --symlink-install --cmake-clean-cache"

COPY ./entrypoint.bash entrypoint.bash
RUN sudo chmod +x entrypoint.bash
